// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjUID-fyXDduw6P2H1Gac-xtAN7QtFSdo',
    appId: '1:1037414646354:web:d9adef26524b49f09ed58b',
    messagingSenderId: '1037414646354',
    projectId: 'chat-48aec',
    authDomain: 'chat-48aec.firebaseapp.com',
    storageBucket: 'chat-48aec.appspot.com',
    measurementId: 'G-15PK9K3GYR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_suqL3N_gwEG3A7VFvj_yP5RobaCiXv8',
    appId: '1:1037414646354:android:b4df4d5f849f41c79ed58b',
    messagingSenderId: '1037414646354',
    projectId: 'chat-48aec',
    storageBucket: 'chat-48aec.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYVloKbEGJFO6JDIj0F9jfncgwgSzbAcc',
    appId: '1:1037414646354:ios:3195249bb02596889ed58b',
    messagingSenderId: '1037414646354',
    projectId: 'chat-48aec',
    storageBucket: 'chat-48aec.appspot.com',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYVloKbEGJFO6JDIj0F9jfncgwgSzbAcc',
    appId: '1:1037414646354:ios:3195249bb02596889ed58b',
    messagingSenderId: '1037414646354',
    projectId: 'chat-48aec',
    storageBucket: 'chat-48aec.appspot.com',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjUID-fyXDduw6P2H1Gac-xtAN7QtFSdo',
    appId: '1:1037414646354:web:57a7b31c9f29ea769ed58b',
    messagingSenderId: '1037414646354',
    projectId: 'chat-48aec',
    authDomain: 'chat-48aec.firebaseapp.com',
    storageBucket: 'chat-48aec.appspot.com',
    measurementId: 'G-4L3M1WFY56',
  );
}
